- name: Setup luals LSP
  ansible.builtin.git:
    repo: "git@github.com:LuaLS/lua-language-server"
    recursive: yes
    dest: "{{ personal }}/lua-language-server"
  tags:
    - install
    - lsp

- name: build the luals LSP
  ansible.builtin.shell:
    cmd: ./make.sh
    chdir: "{{ personal }}/lua-language-server"
  tags:
    - install
    - lsp
