- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim

- name: Clone Neovim
  become: yes
  pacman:
    name:
      - neovim
  tags:
    - install
    - neovim

- name: Neovim Plugin Development 1
  become: yes
  pacman:
    name:
      - luarocks
  tags:
    - install
    - neovim

- name: Neovim Plugin Development 2 luacheck
  become: yes
  shell: luarocks install luacheck
  tags:
    - install
    - neovim
