- name: Install ZSH
  pacman:
    name:
      - zsh
  become: yes
  tags: &tags_for_zsh_tasks ['install', 'productivity', 'dotfiles', 'zsh']

- name: Change shell to zsh
  shell: sudo chsh -s $(which zsh) $(whoami)
  tags: *tags_for_zsh_tasks

- name: Check that the somefile.conf exists
  stat:
    path: /home/{{ lookup('env', 'USER') }}/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: *tags_for_zsh_tasks
  when: not oh_my_stats.stat.exists
  become_user: "{{ lookup('env', 'USER') }}"

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugin/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks
